<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\DishStatus;
use App\Enums\FiveElement;
use App\Enums\MealSlot;
use App\Models\Dish;
use Illuminate\Database\Seeder;

class DishSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->dishes() as $row) {
            Dish::query()->updateOrCreate(
                ['slug' => $row['slug']],
                array_merge($row, [
                    'status' => DishStatus::Published,
                    'source' => 'system',
                ]),
            );
        }
    }

    /**
     * Catalog món VN phổ biến — phủ ma trận bữa × nhẹ/chính × ngoài/tự nấu.
     * calories_kcal + serving_grams luôn đi cặp (khẩu phần chuẩn để quy đổi gram/kcal).
     *
     * @return list<array<string, mixed>>
     */
    private function dishes(): array
    {
        $b = MealSlot::Breakfast->value;
        $l = MealSlot::Lunch->value;
        $d = MealSlot::Dinner->value;

        return [
            // ── Sáng Việt ──────────────────────────────────────────────
            $this->dish(
                name: 'Phở bò',
                slug: 'pho-bo',
                emoji: '🍜',
                summary: 'Phở bò truyền thống — nước dùng đậm đà.',
                slots: [$b, $l],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Water,
                kcal: 450,
                grams: 500,
                cookMinutes: 90,
                ingredients: [
                    ['name' => 'Bánh phở', 'amount' => '200g'],
                    ['name' => 'Thịt bò', 'amount' => '100g'],
                    ['name' => 'Xương bò', 'amount' => '500g'],
                    ['name' => 'Hành, rau thơm', 'amount' => 'vừa đủ'],
                ],
                steps: ['Hầm xương lấy nước dùng', 'Trần bánh phở', 'Xếp thịt, chan nước, thêm rau'],
                benefits: 'Dễ tiêu, ấm bụng buổi sáng.',
                harms: 'Nhiều natrium nếu ăn nhiều nước dùng.',
                advice: 'Thêm chanh và ớt tuỳ khẩu vị.',
                keywords: 'pho bo noodle',
            ),

            $this->dish(
                name: 'Bánh mì thịt',
                slug: 'banh-mi-thit',
                emoji: '🥖',
                summary: 'Bánh mì thịt nguội / đồ chua — nhanh gọn.',
                slots: [$b, $l],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Earth,
                kcal: 380,
                grams: 220,
                cookMinutes: 10,
                ingredients: [
                    ['name' => 'Bánh mì', 'amount' => '1 ổ'],
                    ['name' => 'Thịt nguội / pate', 'amount' => 'vừa'],
                    ['name' => 'Đồ chua, rau', 'amount' => 'vừa'],
                ],
                steps: ['Nướng nhẹ bánh', 'Phết pate, xếp thịt và rau', 'Rưới tương ớt'],
                benefits: 'Tiện mang đi, đủ no nhẹ.',
                harms: 'Vỏ bánh nhiều gluten.',
                advice: 'Chọn ổ nóng giòn.',
                keywords: 'banh mi sandwich',
            ),

            $this->dish(
                name: 'Xôi gà',
                slug: 'xoi-ga',
                emoji: '🍚',
                summary: 'Xôi gà mặn — no lâu, hợp bữa sáng.',
                slots: [$b],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Earth,
                kcal: 520,
                grams: 350,
                cookMinutes: 40,
                ingredients: [
                    ['name' => 'Gạo nếp', 'amount' => '200g'],
                    ['name' => 'Thịt gà', 'amount' => '150g'],
                    ['name' => 'Hành phi', 'amount' => 'vừa'],
                ],
                steps: ['Ngâm nếp, hấp xôi', 'Luộc/xé gà trộn gia vị', 'Rắc hành phi'],
                benefits: 'Năng lượng cao cho buổi sáng bận rộn.',
                harms: 'Khó tiêu nếu ăn quá no.',
                advice: 'Ăn kèm dưa leo.',
                keywords: 'xoi sticky rice',
            ),

            $this->dish(
                name: 'Cháo gà',
                slug: 'chao-ga',
                emoji: '🥣',
                summary: 'Cháo gà loãng — nhẹ bụng.',
                slots: [$b, $d],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Water,
                kcal: 280,
                grams: 400,
                cookMinutes: 35,
                ingredients: [
                    ['name' => 'Gạo', 'amount' => '80g'],
                    ['name' => 'Thịt gà', 'amount' => '100g'],
                    ['name' => 'Gừng', 'amount' => 'ít'],
                ],
                steps: ['Nấu cháo nhừ', 'Cho gà xé và gừng', 'Nêm vừa miệng'],
                benefits: 'Dễ tiêu, hợp khi mệt.',
                harms: 'Ít chất xơ nếu không thêm rau.',
                advice: 'Rắc tiêu và hành lá.',
                keywords: 'chao porridge',
            ),

            $this->dish(
                name: 'Bún bò Huế',
                slug: 'bun-bo-hue',
                emoji: '🌶️',
                summary: 'Bún bò Huế cay nồng đặc trưng.',
                slots: [$b, $l],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Fire,
                kcal: 550,
                grams: 550,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Ấm người, giàu protein.',
                harms: 'Cay và nhiều dầu — dạ dày yếu nên hạn chế.',
                advice: 'Gọi mức cay vừa phải.',
                keywords: 'bun bo hue',
            ),

            $this->dish(
                name: 'Hủ tiếu',
                slug: 'hu-tieu',
                emoji: '🍜',
                summary: 'Hủ tiếu Nam Vang / xương — sáng hoặc trưa.',
                slots: [$b, $l],
                light: true,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Water,
                kcal: 420,
                grams: 480,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Nước trong, topping đa dạng.',
                harms: 'Có thể nhiều bột năng.',
                advice: 'Gọi khô nếu muốn bớt nước dùng.',
                keywords: 'hu tieu',
            ),

            $this->dish(
                name: 'Bánh cuốn',
                slug: 'banh-cuon',
                emoji: '🥟',
                summary: 'Bánh cuốn nhân thịt — nhẹ bụng.',
                slots: [$b, $l],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Earth,
                kcal: 300,
                grams: 280,
                cookMinutes: 35,
                ingredients: [
                    ['name' => 'Bột gạo', 'amount' => '200g'],
                    ['name' => 'Thịt băm + mộc nhĩ', 'amount' => '150g'],
                    ['name' => 'Nước mắm chua ngọt', 'amount' => 'chén'],
                ],
                steps: ['Tráng bánh mỏng', 'Gói nhân', 'Chan nước chấm, chả'],
                benefits: 'Dễ tiêu hơn phở đặc.',
                harms: 'Nước chấm ngọt — hạn chế đường.',
                advice: 'Ăn kèm rau thơm.',
                keywords: 'banh cuon',
            ),

            $this->dish(
                name: 'Cháo lòng',
                slug: 'chao-long',
                emoji: '🥣',
                summary: 'Cháo lòng — đặc sản sáng.',
                slots: [$b],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Water,
                kcal: 400,
                grams: 400,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Ấm bụng, no.',
                harms: 'Không hợp người kỵ nội tạng / mỡ.',
                advice: 'Chọn quán sạch sẽ.',
                keywords: 'chao long',
            ),

            $this->dish(
                name: 'Bánh bao',
                slug: 'banh-bao',
                emoji: '🥟',
                summary: 'Bánh bao nhân thịt/trứng — mang đi.',
                slots: [$b, $l],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Earth,
                kcal: 280,
                grams: 150,
                cookMinutes: 45,
                ingredients: [
                    ['name' => 'Bột mì men', 'amount' => '300g'],
                    ['name' => 'Nhân thịt', 'amount' => '200g'],
                ],
                steps: ['Nhồi bột, ủ', 'Gói nhân', 'Hấp chín'],
                benefits: 'Tiện, no vừa.',
                harms: 'Vỏ bột tinh bột cao.',
                advice: 'Hấp lại nếu để nguội.',
                keywords: 'banh bao bun',
            ),

            $this->dish(
                name: 'Cháo yến mạch',
                slug: 'chao-yen-mach',
                emoji: '🥣',
                summary: 'Cháo yến mạch trái cây — sáng healthy.',
                slots: [$b],
                light: true,
                main: true,
                dineOut: false,
                cookHome: true,
                element: FiveElement::Wood,
                kcal: 220,
                grams: 300,
                cookMinutes: 12,
                ingredients: [
                    ['name' => 'Yến mạch', 'amount' => '40g'],
                    ['name' => 'Sữa / nước', 'amount' => '200ml'],
                    ['name' => 'Trái cây, hạt', 'amount' => 'vừa'],
                ],
                steps: ['Nấu yến mạch', 'Thêm trái cây', 'Rắc hạt'],
                benefits: 'No lâu, tốt tiêu hoá.',
                harms: 'Một số người đầy hơi với yến mạch.',
                advice: 'Ngâm qua đêm cho mềm.',
                keywords: 'oat porridge',
            ),

            $this->dish(
                name: 'Cà phê sữa đá',
                slug: 'ca-phe-sua-da',
                emoji: '☕',
                summary: 'Cà phê sữa đá — “bữa” nhẹ sáng.',
                slots: [$b],
                light: true,
                main: false,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Water,
                kcal: 180,
                grams: 250,
                cookMinutes: 10,
                ingredients: [
                    ['name' => 'Cà phê phin', 'amount' => '1 phin'],
                    ['name' => 'Sữa đặc', 'amount' => '2 muỗng'],
                    ['name' => 'Đá', 'amount' => 'cốc'],
                ],
                steps: ['Pha phin', 'Khuấy sữa', 'Thêm đá'],
                benefits: 'Tỉnh táo buổi sáng.',
                harms: 'Cafein và đường — hạn chế buổi tối.',
                advice: 'Có thể dùng sữa tươi ít đường.',
                keywords: 'ca phe coffee',
            ),

            // ── Trưa / tối cơm & bún ───────────────────────────────────
            $this->dish(
                name: 'Cơm tấm sườn',
                slug: 'com-tam-suon',
                emoji: '🍛',
                summary: 'Cơm tấm sườn bì chả — bữa trưa kinh điển.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Earth,
                kcal: 680,
                grams: 450,
                cookMinutes: 45,
                ingredients: [
                    ['name' => 'Cơm tấm', 'amount' => '1 đĩa'],
                    ['name' => 'Sườn nướng', 'amount' => '1 miếng'],
                    ['name' => 'Đồ chua, mỡ hành', 'amount' => 'vừa'],
                ],
                steps: ['Ướp và nướng sườn', 'Nấu cơm tấm', 'Bày đĩa với đồ chua'],
                benefits: 'No đủ cho buổi chiều làm việc.',
                harms: 'Calo cao nếu thêm nhiều mỡ hành.',
                advice: 'Bớt nước mắm ngọt nếu cần giảm đường.',
                keywords: 'com tam broken rice',
            ),

            $this->dish(
                name: 'Bún chả',
                slug: 'bun-cha',
                emoji: '🥩',
                summary: 'Bún chả Hà Nội — thịt nướng nước chấm.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Fire,
                kcal: 520,
                grams: 450,
                cookMinutes: 40,
                ingredients: [
                    ['name' => 'Bún', 'amount' => '200g'],
                    ['name' => 'Thịt ba chỉ / chả', 'amount' => '150g'],
                    ['name' => 'Rau sống', 'amount' => '1 đĩa'],
                ],
                steps: ['Nướng thịt', 'Pha nước chấm', 'Chấm thịt với bún và rau'],
                benefits: 'Cân bằng thịt và rau sống.',
                harms: 'Nướng than nhiều có thể có chất khó lành.',
                advice: 'Ăn nhiều rau.',
                keywords: 'bun cha',
            ),

            $this->dish(
                name: 'Bún riêu',
                slug: 'bun-rieu',
                emoji: '🦀',
                summary: 'Bún riêu cua — chua nhẹ dễ ăn.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Water,
                kcal: 480,
                grams: 500,
                cookMinutes: 50,
                ingredients: [
                    ['name' => 'Bún', 'amount' => '200g'],
                    ['name' => 'Riêu cua', 'amount' => '1 bát'],
                    ['name' => 'Cà chua, đậu', 'amount' => 'vừa'],
                ],
                steps: ['Nấu nước dùng cà chua', 'Thả riêu', 'Chan bún, thêm rau'],
                benefits: 'Giàu canxi từ cua (tuỳ công thức).',
                harms: 'Có thể tanh với người nhạy cảm.',
                advice: 'Thêm chanh và rau sống.',
                keywords: 'bun rieu',
            ),

            $this->dish(
                name: 'Mì Quảng',
                slug: 'mi-quang',
                emoji: '🥘',
                summary: 'Mì Quảng — đặc sản miền Trung.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Earth,
                kcal: 560,
                grams: 420,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Nhiều topping, no lâu.',
                harms: 'Nước dùng đặc, cân nhắc lượng dầu.',
                advice: 'Ăn kèm bánh tráng mè.',
                keywords: 'mi quang',
            ),

            $this->dish(
                name: 'Cơm gà',
                slug: 'com-ga',
                emoji: '🍗',
                summary: 'Cơm gà Hội An / xé phay.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Metal,
                kcal: 540,
                grams: 400,
                cookMinutes: 40,
                ingredients: [
                    ['name' => 'Cơm', 'amount' => '1 chén'],
                    ['name' => 'Gà luộc', 'amount' => '1/4 con'],
                    ['name' => 'Nước mắm gừng', 'amount' => 'chén nhỏ'],
                ],
                steps: ['Luộc gà, xé thịt', 'Nấu cơm với nước luộc', 'Chấm mắm gừng'],
                benefits: 'Protein tốt, dễ chế biến.',
                harms: 'Da gà nhiều mỡ.',
                advice: 'Bỏ da nếu muốn nhẹ hơn.',
                keywords: 'com ga chicken rice',
            ),

            $this->dish(
                name: 'Canh chua cá',
                slug: 'canh-chua-ca',
                emoji: '🐟',
                summary: 'Canh chua cá — thanh mát bữa cơm.',
                slots: [$l, $d],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Wood,
                kcal: 220,
                grams: 350,
                cookMinutes: 25,
                ingredients: [
                    ['name' => 'Cá', 'amount' => '300g'],
                    ['name' => 'Me / cà chua', 'amount' => 'vừa'],
                    ['name' => 'Giá, bạc hà', 'amount' => 'vừa'],
                ],
                steps: ['Nấu nước me/cà chua', 'Cho cá chín', 'Nêm và thêm rau'],
                benefits: 'Nhiều vitamin từ rau.',
                harms: 'Xương cá — cẩn thận khi ăn.',
                advice: 'Ăn nóng với cơm.',
                keywords: 'canh chua',
            ),

            $this->dish(
                name: 'Bún thịt nướng',
                slug: 'bun-thit-nuong',
                emoji: '🥩',
                summary: 'Bún thịt nướng — trưa/tối.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Fire,
                kcal: 500,
                grams: 420,
                cookMinutes: 35,
                ingredients: [
                    ['name' => 'Bún', 'amount' => '200g'],
                    ['name' => 'Thịt nướng', 'amount' => '120g'],
                    ['name' => 'Đồ chua, rau', 'amount' => 'vừa'],
                ],
                steps: ['Ướp nướng thịt', 'Bày bún rau', 'Chan nước mắm'],
                benefits: 'Cân bằng tinh bột – đạm – rau.',
                harms: 'Nước mắm ngọt nhiều đường.',
                advice: 'Xin nước mắm riêng.',
                keywords: 'bun thit nuong',
            ),

            $this->dish(
                name: 'Bánh xèo',
                slug: 'banh-xeo',
                emoji: '🥞',
                summary: 'Bánh xèo giòn — cuốn rau sống.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Earth,
                kcal: 480,
                grams: 300,
                cookMinutes: 30,
                ingredients: [
                    ['name' => 'Bột bánh xèo', 'amount' => '200g'],
                    ['name' => 'Tôm thịt giá', 'amount' => 'nhân'],
                    ['name' => 'Rau sống', 'amount' => '1 đĩa'],
                ],
                steps: ['Pha bột', 'Đổ khuôn chiên giòn', 'Cuốn lá và chấm'],
                benefits: 'Nhiều rau khi cuốn.',
                harms: 'Chiên dầu — ăn vừa phải.',
                advice: 'Làm mỏng để giòn và nhẹ hơn.',
                keywords: 'banh xeo',
            ),

            $this->dish(
                name: 'Cơm rang',
                slug: 'com-rang',
                emoji: '🍳',
                summary: 'Cơm rang trứng/dưa bò — tận dụng cơm nguội.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Earth,
                kcal: 500,
                grams: 350,
                cookMinutes: 15,
                ingredients: [
                    ['name' => 'Cơm nguội', 'amount' => '1–2 chén'],
                    ['name' => 'Trứng / thịt', 'amount' => 'vừa'],
                    ['name' => 'Hành, gia vị', 'amount' => 'vừa'],
                ],
                steps: ['Phi thơm hành', 'Đảo cơm lửa lớn', 'Cho trứng/thịt'],
                benefits: 'Nhanh, giảm lãng phí cơm.',
                harms: 'Dễ mặn và dầu.',
                advice: 'Ít nước tương, nhiều rau.',
                keywords: 'com rang fried rice',
            ),

            $this->dish(
                name: 'Mì xào bò',
                slug: 'mi-xao-bo',
                emoji: '🍝',
                summary: 'Mì xào bò — no, hợp tối.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Metal,
                kcal: 600,
                grams: 400,
                cookMinutes: 25,
                ingredients: [
                    ['name' => 'Mì trứng', 'amount' => '1 vắt'],
                    ['name' => 'Thịt bò', 'amount' => '100g'],
                    ['name' => 'Rau cải', 'amount' => 'vừa'],
                ],
                steps: ['Luộc mì', 'Xào bò và rau', 'Đảo đều với mì'],
                benefits: 'Nhanh no, đủ chất.',
                harms: 'Nhiều dầu khi xào.',
                advice: 'Lửa lớn, ít dầu.',
                keywords: 'mi xao noodles',
            ),

            $this->dish(
                name: 'Bánh canh',
                slug: 'banh-canh',
                emoji: '🍜',
                summary: 'Bánh canh cua / giò — đặc sệt.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Water,
                kcal: 480,
                grams: 450,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'No lâu, ấm bụng.',
                harms: 'Nước đặc nhiều tinh bột.',
                advice: 'Bớt bánh nếu muốn nhẹ.',
                keywords: 'banh canh',
            ),

            $this->dish(
                name: 'Gỏi cuốn',
                slug: 'goi-cuon',
                emoji: '🥗',
                summary: 'Gỏi cuốn tôm thịt — tươi mát.',
                slots: [$l, $d],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Wood,
                kcal: 200,
                grams: 180,
                cookMinutes: 20,
                ingredients: [
                    ['name' => 'Bánh tráng', 'amount' => '4 cái'],
                    ['name' => 'Tôm, thịt', 'amount' => 'vừa'],
                    ['name' => 'Bún, rau', 'amount' => 'vừa'],
                ],
                steps: ['Luộc tôm thịt', 'Cuốn với bún rau', 'Chấm tương hoặc mắm nêm'],
                benefits: 'Ít dầu, nhiều rau.',
                harms: 'Nước chấm béo nếu dùng tương đậu phộng nhiều.',
                advice: 'Cuốn vừa ăn, không để khô.',
                keywords: 'goi cuon spring roll',
            ),

            $this->dish(
                name: 'Nem rán',
                slug: 'nem-ran',
                emoji: '🥟',
                summary: 'Nem rán / chả giò — món phụ hoặc chính nhẹ.',
                slots: [$l, $d],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Fire,
                kcal: 350,
                grams: 150,
                cookMinutes: 40,
                ingredients: [
                    ['name' => 'Bánh đa nem', 'amount' => '10 cái'],
                    ['name' => 'Thịt + miến + rau', 'amount' => 'nhân'],
                    ['name' => 'Dầu chiên', 'amount' => 'đủ'],
                ],
                steps: ['Gói nem', 'Chiên vàng', 'Chấm nước mắm'],
                benefits: 'Giòn ngon, hợp sum họp.',
                harms: 'Chiên ngập dầu — không nên thường xuyên.',
                advice: 'Chiên air-fryer nếu có.',
                keywords: 'nem spring roll fried',
            ),

            // ── Chay ───────────────────────────────────────────────────
            $this->dish(
                name: 'Cơm chay',
                slug: 'com-chay',
                emoji: '🌱',
                summary: 'Cơm chay — đạm thực vật.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Wood,
                kcal: 450,
                grams: 400,
                cookMinutes: 30,
                ingredients: [
                    ['name' => 'Cơm', 'amount' => '1 chén'],
                    ['name' => 'Đậu phụ / nấm', 'amount' => '150g'],
                    ['name' => 'Rau củ', 'amount' => '1 đĩa'],
                ],
                steps: ['Xào nấm đậu', 'Nấu canh rau', 'Bày mâm cơm chay'],
                benefits: 'Thân thiện người ăn chay.',
                harms: 'Cần đa dạng nguồn đạm thực vật.',
                advice: 'Hạn chế chiên nhiều.',
                keywords: 'com chay vegetarian',
            ),

            $this->dish(
                name: 'Phở chay',
                slug: 'pho-chay',
                emoji: '🌿',
                summary: 'Phở chay — nước dùng rau củ.',
                slots: [$b, $l],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Wood,
                kcal: 320,
                grams: 480,
                cookMinutes: 40,
                ingredients: [
                    ['name' => 'Bánh phở', 'amount' => '200g'],
                    ['name' => 'Nấm, đậu', 'amount' => 'vừa'],
                    ['name' => 'Rau thơm', 'amount' => 'vừa'],
                ],
                steps: ['Nấu nước dùng rau củ', 'Trần bánh', 'Chan và thêm topping'],
                benefits: 'Nhẹ, phù hợp ngày chay.',
                harms: 'Ít protein nếu thiếu đậu/nấm.',
                advice: 'Thêm tàu hũ ky hoặc đậu phụ.',
                keywords: 'pho chay',
            ),

            $this->dish(
                name: 'Bún chay',
                slug: 'bun-chay',
                emoji: '🥬',
                summary: 'Bún chay nước dùng rau củ — nhẹ, thanh.',
                slots: [$l, $d],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Wood,
                kcal: 350,
                grams: 450,
                cookMinutes: 30,
                ingredients: [
                    ['name' => 'Bún', 'amount' => '200g'],
                    ['name' => 'Nấm, đậu hũ', 'amount' => '150g'],
                    ['name' => 'Rau sống', 'amount' => '1 đĩa'],
                ],
                steps: ['Nấu nước dùng rau củ', 'Xào nấm đậu', 'Chan bún, thêm rau'],
                benefits: 'Ít dầu, nhiều xơ.',
                harms: 'Nước chấm ngọt nếu lạm dụng.',
                advice: 'Thêm chanh, ớt tuỳ khẩu vị.',
                keywords: 'bun chay vegetarian',
            ),

            // ── Tự nấu đơn giản / healthy ──────────────────────────────
            $this->dish(
                name: 'Trứng chiên',
                slug: 'trung-chien',
                emoji: '🍳',
                summary: 'Trứng chiên — tự nấu siêu nhanh.',
                slots: [$b, $l, $d],
                light: true,
                main: true,
                dineOut: false,
                cookHome: true,
                element: FiveElement::Metal,
                kcal: 180,
                grams: 100,
                cookMinutes: 8,
                ingredients: [
                    ['name' => 'Trứng gà', 'amount' => '2 quả'],
                    ['name' => 'Hành lá', 'amount' => 'ít'],
                    ['name' => 'Dầu ăn', 'amount' => '1 muỗng'],
                ],
                steps: ['Đánh trứng với muối hành', 'Chiên vàng hai mặt', 'Cắt miếng ăn với cơm/rau'],
                benefits: 'Protein rẻ, nhanh.',
                harms: 'Chiên nhiều dầu tăng calo.',
                advice: 'Có thể hấp/luộc thay chiên.',
                keywords: 'trung egg',
            ),

            $this->dish(
                name: 'Ức gà hấp',
                slug: 'uc-ga-hap',
                emoji: '🥗',
                summary: 'Ức gà hấp / áp chảo — nhẹ.',
                slots: [$l, $d],
                light: true,
                main: true,
                dineOut: false,
                cookHome: true,
                element: FiveElement::Metal,
                kcal: 250,
                grams: 180,
                cookMinutes: 20,
                ingredients: [
                    ['name' => 'Ức gà', 'amount' => '150g'],
                    ['name' => 'Gia vị', 'amount' => 'vừa'],
                    ['name' => 'Rau củ', 'amount' => '1 đĩa'],
                ],
                steps: ['Ướp nhẹ ức gà', 'Hấp hoặc áp chảo', 'Ăn kèm salad'],
                benefits: 'Ít béo, giàu protein.',
                harms: 'Có thể khô nếu nấu quá lửa.',
                advice: 'Ướp yogurt hoặc mật ong loãng cho mềm.',
                keywords: 'chicken breast',
            ),

            $this->dish(
                name: 'Rau xào tỏi',
                slug: 'rau-xao-toi',
                emoji: '🥬',
                summary: 'Rau xanh xào tỏi — món phụ hoặc ăn nhẹ.',
                slots: [$l, $d],
                light: true,
                main: false,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Wood,
                kcal: 90,
                grams: 200,
                cookMinutes: 10,
                ingredients: [
                    ['name' => 'Rau cải / bắp cải', 'amount' => '300g'],
                    ['name' => 'Tỏi', 'amount' => '3 tép'],
                    ['name' => 'Dầu', 'amount' => '1 muỗng'],
                ],
                steps: ['Phi tỏi thơm', 'Xào rau lửa lớn', 'Nêm nước mắm loãng'],
                benefits: 'Chất xơ, vitamin.',
                harms: 'Xào kỹ quá mất chất xanh.',
                advice: 'Không cho quá nhiều dầu.',
                keywords: 'rau xao vegetable',
            ),

            $this->dish(
                name: 'Canh rau',
                slug: 'canh-rau-ngot',
                emoji: '🌿',
                summary: 'Canh rau ngót / rau củ — món phụ tự nấu.',
                slots: [$l, $d],
                light: true,
                main: false,
                dineOut: false,
                cookHome: true,
                element: FiveElement::Wood,
                kcal: 60,
                grams: 250,
                cookMinutes: 15,
                ingredients: [
                    ['name' => 'Rau ngót / bí', 'amount' => '200g'],
                    ['name' => 'Thịt băm (tuỳ)', 'amount' => '50g'],
                ],
                steps: ['Nấu nước dùng nhẹ', 'Cho rau vừa chín tới', 'Nêm nhạt'],
                benefits: 'Thanh, nhiều vitamin.',
                harms: 'Nấu lâu mất màu xanh.',
                advice: 'Ăn kèm cơm và món mặn.',
                keywords: 'canh rau',
            ),

            $this->dish(
                name: 'Salad gà',
                slug: 'salad-ga',
                emoji: '🥗',
                summary: 'Salad ức gà — ăn nhẹ / chính nhẹ.',
                slots: [$l, $d],
                light: true,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Wood,
                kcal: 280,
                grams: 250,
                cookMinutes: 15,
                ingredients: [
                    ['name' => 'Ức gà', 'amount' => '120g'],
                    ['name' => 'Xà lách, cà chua', 'amount' => '1 tô'],
                    ['name' => 'Sốt dầu giấm', 'amount' => '2 muỗng'],
                ],
                steps: ['Luộc/nướng ức gà', 'Trộn rau', 'Chan sốt vừa đủ'],
                benefits: 'Ít tinh bột, nhiều xơ.',
                harms: 'Sốt kem/mayo làm tăng calo.',
                advice: 'Ưu tiên sốt chua nhẹ.',
                keywords: 'salad chicken',
            ),

            $this->dish(
                name: 'Cá hấp gừng',
                slug: 'ca-hap-gung',
                emoji: '🐟',
                summary: 'Cá hấp gừng hành — tự nấu thanh đạm.',
                slots: [$l, $d],
                light: true,
                main: true,
                dineOut: false,
                cookHome: true,
                element: FiveElement::Metal,
                kcal: 280,
                grams: 250,
                cookMinutes: 25,
                ingredients: [
                    ['name' => 'Cá (diêu hồng / basa)', 'amount' => '300g'],
                    ['name' => 'Gừng, hành', 'amount' => 'vừa'],
                    ['name' => 'Nước tương', 'amount' => '2 muỗng'],
                ],
                steps: ['Rửa cá, xếp gừng', 'Hấp 15–20 phút', 'Chan nước tương hành'],
                benefits: 'Protein, omega-3, ít dầu.',
                harms: 'Xương cá — cẩn thận.',
                advice: 'Ăn kèm rau luộc.',
                keywords: 'ca hap steamed fish',
            ),

            $this->dish(
                name: 'Đậu phụ sốt cà',
                slug: 'dau-phu-sot-ca',
                emoji: '🍅',
                summary: 'Đậu phụ sốt cà chua — món mặn tự nấu.',
                slots: [$l, $d],
                light: true,
                main: true,
                dineOut: false,
                cookHome: true,
                element: FiveElement::Metal,
                kcal: 220,
                grams: 280,
                cookMinutes: 20,
                ingredients: [
                    ['name' => 'Đậu phụ', 'amount' => '300g'],
                    ['name' => 'Cà chua', 'amount' => '2 quả'],
                    ['name' => 'Hành, tỏi', 'amount' => 'vừa'],
                ],
                steps: ['Chiên/áp chảo đậu', 'Xào cà chua thành sốt', 'Kho/sốt nhẹ cùng đậu'],
                benefits: 'Đạm thực vật rẻ, dễ làm.',
                harms: 'Chiên đậu nhiều dầu tăng calo.',
                advice: 'Luộc/hấp đậu thay chiên nếu muốn nhẹ.',
                keywords: 'tofu tomato',
            ),

            $this->dish(
                name: 'Thịt kho trứng',
                slug: 'thit-kho-trung',
                emoji: '🥚',
                summary: 'Thịt kho tàu / kho trứng — cơm nhà Việt.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: false,
                cookHome: true,
                element: FiveElement::Metal,
                kcal: 520,
                grams: 300,
                cookMinutes: 50,
                ingredients: [
                    ['name' => 'Thịt ba chỉ', 'amount' => '300g'],
                    ['name' => 'Trứng', 'amount' => '3 quả'],
                    ['name' => 'Nước dừa, nước mắm', 'amount' => 'vừa'],
                ],
                steps: ['Luộc/rán trứng', 'Kho thịt với nước dừa', 'Nêm vừa, ninh mềm'],
                benefits: 'No, hợp cơm nóng.',
                harms: 'Nhiều mỡ và đường nâu.',
                advice: 'Hớt bớt mỡ nổi, ăn kèm dưa chua.',
                keywords: 'thit kho thit kho tau',
            ),

            // ── Ăn nhẹ / snack ─────────────────────────────────────────
            $this->dish(
                name: 'Sữa chua trái cây',
                slug: 'sua-chua-trai-cay',
                emoji: '🍓',
                summary: 'Sữa chua trái cây — ăn nhẹ.',
                slots: [$b, $l, $d],
                light: true,
                main: false,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Earth,
                kcal: 150,
                grams: 200,
                cookMinutes: 5,
                ingredients: [
                    ['name' => 'Sữa chua', 'amount' => '1 hộp'],
                    ['name' => 'Trái cây', 'amount' => '100g'],
                ],
                steps: ['Cắt trái cây', 'Trộn với sữa chua', 'Thêm chút mật ong (tuỳ)'],
                benefits: 'Lợi khuẩn, dễ làm.',
                harms: 'Sữa chua có đường — chọn loại ít đường.',
                advice: 'Dùng làm bữa phụ chiều.',
                keywords: 'yogurt fruit',
            ),

            $this->dish(
                name: 'Trái cây tươi',
                slug: 'trai-cay-toi',
                emoji: '🍎',
                summary: 'Đĩa trái cây tươi — snack lành.',
                slots: [$b, $l, $d],
                light: true,
                main: false,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Wood,
                kcal: 100,
                grams: 200,
                cookMinutes: 3,
                ingredients: [
                    ['name' => 'Trái cây theo mùa', 'amount' => '200g'],
                ],
                steps: ['Rửa sạch', 'Cắt miếng', 'Thưởng thức ngay'],
                benefits: 'Vitamin, hydrat.',
                harms: 'Một số trái nhiều đường tự nhiên.',
                advice: 'Kết hợp 2–3 loại màu.',
                keywords: 'fruit',
            ),

            $this->dish(
                name: 'Bánh tráng trộn',
                slug: 'banh-trang-tron',
                emoji: '🥙',
                summary: 'Bánh tráng trộn — ăn vặt đường phố.',
                slots: [$l, $d],
                light: true,
                main: false,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Fire,
                kcal: 320,
                grams: 200,
                cookMinutes: 15,
                ingredients: [
                    ['name' => 'Bánh tráng', 'amount' => '2–3 cái'],
                    ['name' => 'Xoài, khô bò', 'amount' => 'vừa'],
                    ['name' => 'Tương ớt, trứng cút', 'amount' => 'vừa'],
                ],
                steps: ['Cắt bánh tráng', 'Trộn topping và sốt', 'Ăn ngay cho giòn'],
                benefits: 'Vui miệng, chia sẻ nhóm.',
                harms: 'Nhiều gia vị và calo ẩn.',
                advice: 'Bớt sốt dầu nếu muốn nhẹ.',
                keywords: 'banh trang',
            ),

            $this->dish(
                name: 'Chè ba màu',
                slug: 'che-ba-mau',
                emoji: '🍧',
                summary: 'Chè ba màu — tráng miệng / ăn nhẹ.',
                slots: [$l, $d],
                light: true,
                main: false,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Earth,
                kcal: 280,
                grams: 250,
                cookMinutes: 20,
                ingredients: [
                    ['name' => 'Đậu, thạch, bột báng', 'amount' => 'vừa'],
                    ['name' => 'Nước cốt dừa', 'amount' => 'vừa'],
                ],
                steps: ['Nấu từng lớp đậu', 'Xếp ly', 'Chan cốt dừa'],
                benefits: 'Giải nhiệt, vui miệng.',
                harms: 'Nhiều đường.',
                advice: 'Xin ít đường khi mua.',
                keywords: 'che dessert',
            ),

            $this->dish(
                name: 'Sinh tố bơ',
                slug: 'sinh-to-bo',
                emoji: '🥑',
                summary: 'Sinh tố bơ — no nhẹ.',
                slots: [$b, $l],
                light: true,
                main: false,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Earth,
                kcal: 320,
                grams: 300,
                cookMinutes: 8,
                ingredients: [
                    ['name' => 'Bơ', 'amount' => '1/2 quả'],
                    ['name' => 'Sữa / đá', 'amount' => 'vừa'],
                    ['name' => 'Đường (tuỳ)', 'amount' => 'ít'],
                ],
                steps: ['Xay bơ với sữa đá', 'Nêm nhẹ', 'Uống ngay'],
                benefits: 'Chất béo tốt, no lâu.',
                harms: 'Calo cao nếu nhiều sữa đặc.',
                advice: 'Bớt đường.',
                keywords: 'sinh to smoothie',
            ),

            $this->dish(
                name: 'Súp cua',
                slug: 'sup-cua',
                emoji: '🥣',
                summary: 'Súp cua — khai vị hoặc ăn nhẹ.',
                slots: [$l, $d],
                light: true,
                main: false,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Water,
                kcal: 200,
                grams: 250,
                cookMinutes: 25,
                ingredients: [
                    ['name' => 'Thịt cua', 'amount' => '100g'],
                    ['name' => 'Trứng', 'amount' => '1 quả'],
                    ['name' => 'Bắp / nấm', 'amount' => 'vừa'],
                ],
                steps: ['Nấu nước dùng', 'Cho cua và bột năng', 'Đổ trứng tan'],
                benefits: 'Nhẹ bụng, ấm.',
                harms: 'Bột năng nhiều làm đặc calo rỗng.',
                advice: 'Thêm tiêu và rau mùi.',
                keywords: 'sup soup',
            ),

            // ── Ăn ngoài điển hình ─────────────────────────────────────
            $this->dish(
                name: 'Lẩu Thái',
                slug: 'lau-thai',
                emoji: '🍲',
                summary: 'Lẩu Thái — hợp ăn ngoài tối.',
                slots: [$d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Fire,
                kcal: 700,
                grams: 600,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Đa dạng rau và hải sản.',
                harms: 'Nước lẩu cay chua — dạ dày yếu cẩn thận.',
                advice: 'Ưu tiên rau trước, thịt sau.',
                keywords: 'lau hotpot thai',
            ),

            $this->dish(
                name: 'Đồ nướng BBQ',
                slug: 'nuong-bbq',
                emoji: '🔥',
                summary: 'Đồ nướng BBQ — tiệc tối.',
                slots: [$d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Fire,
                kcal: 750,
                grams: 400,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Không khí vui, protein nhiều.',
                harms: 'Thịt nướng cháy có thể không tốt nếu thường xuyên.',
                advice: 'Kẹp nhiều rau sống.',
                keywords: 'nuong grill bbq',
            ),

            $this->dish(
                name: 'Lẩu cá kèo',
                slug: 'lau-ca-keo',
                emoji: '🐟',
                summary: 'Lẩu cá kèo — đặc sản tối.',
                slots: [$d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Water,
                kcal: 550,
                grams: 550,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Ngọt nước, nhiều rau.',
                harms: 'Xương cá nhỏ — cẩn thận.',
                advice: 'Nhúng rau nhiều.',
                keywords: 'lau ca',
            ),

            $this->dish(
                name: 'Ốc',
                slug: 'oc-xao',
                emoji: '🐌',
                summary: 'Ốc xào/luộc — ăn vặt tối.',
                slots: [$d],
                light: true,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Water,
                kcal: 300,
                grams: 250,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Vui miệng, giàu khoáng.',
                harms: 'Vệ sinh ốc rất quan trọng.',
                advice: 'Chọn quán uy tín.',
                keywords: 'oc snail',
            ),

            $this->dish(
                name: 'Mì cay',
                slug: 'mi-cay',
                emoji: '🌶️',
                summary: 'Mì cay Hàn — ăn ngoài / tự nấu gói.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: true,
                element: FiveElement::Fire,
                kcal: 550,
                grams: 400,
                cookMinutes: 12,
                ingredients: [
                    ['name' => 'Mì gói cay', 'amount' => '1 gói'],
                    ['name' => 'Trứng, phô mai (tuỳ)', 'amount' => 'topping'],
                ],
                steps: ['Luộc mì', 'Nêm gói gia vị vừa', 'Thêm topping'],
                benefits: 'Nhanh, “đã” cay.',
                harms: 'Natri và cay cao — không nên thường xuyên.',
                advice: 'Bớt bột cay, thêm rau.',
                keywords: 'mi cay ramyeon',
            ),

            $this->dish(
                name: 'Dimsum',
                slug: 'dimsum',
                emoji: '🥟',
                summary: 'Dimsum hấp — ăn ngoài trưa/sáng muộn.',
                slots: [$b, $l],
                light: true,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Earth,
                kcal: 400,
                grams: 250,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Đa dạng, chia sẻ nhóm.',
                harms: 'Một số món chiên calo cao.',
                advice: 'Ưu tiên hấp hơn chiên.',
                keywords: 'dimsum ha cao',
            ),

            $this->dish(
                name: 'Pizza',
                slug: 'pizza-lat',
                emoji: '🍕',
                summary: 'Pizza — bữa chính ăn ngoài.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Fire,
                kcal: 800,
                grams: 350,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'No, vui miệng.',
                harms: 'Nhiều bột và phô mai.',
                advice: 'Chọn đế mỏng, nhiều rau.',
                keywords: 'pizza',
            ),

            $this->dish(
                name: 'Sushi',
                slug: 'sushi-set',
                emoji: '🍣',
                summary: 'Set sushi / sashimi — ăn ngoài.',
                slots: [$l, $d],
                light: true,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Water,
                kcal: 450,
                grams: 300,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Protein cá, phần nhẹ.',
                harms: 'Cần độ tươi cao.',
                advice: 'Wasabi và gừng hỗ trợ cảm nhận tươi.',
                keywords: 'sushi',
            ),

            $this->dish(
                name: 'Gà rán',
                slug: 'ga-ran',
                emoji: '🍗',
                summary: 'Gà rán — chính hoặc chia sẻ.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Fire,
                kcal: 650,
                grams: 300,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Ngon miệng, no.',
                harms: 'Chiên nhiều dầu.',
                advice: 'Kèm salad, hạn chế nước ngọt.',
                keywords: 'ga ran fried chicken',
            ),

            $this->dish(
                name: 'Bún đậu mắm tôm',
                slug: 'bun-dau-mam-tom',
                emoji: '🥗',
                summary: 'Bún đậu mắm tôm — trưa/tối ăn ngoài.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Earth,
                kcal: 580,
                grams: 450,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'Đa dạng topping, vui miệng.',
                harms: 'Chiên nhiều + mắm tôm nồng.',
                advice: 'Bớt chiên, thêm rau sống.',
                keywords: 'bun dau mam tom',
            ),

            $this->dish(
                name: 'Cơm niêu',
                slug: 'com-nieu',
                emoji: '🍲',
                summary: 'Cơm niêu — cơm cháy, món mặn kèm.',
                slots: [$l, $d],
                light: false,
                main: true,
                dineOut: true,
                cookHome: false,
                element: FiveElement::Earth,
                kcal: 620,
                grams: 450,
                cookMinutes: null,
                ingredients: null,
                steps: null,
                benefits: 'No, hương vị đậm.',
                harms: 'Cơm cháy và món kho nhiều dầu.',
                advice: 'Chia sẻ nhóm, thêm rau.',
                keywords: 'com nieu clay pot',
            ),
        ];
    }

    /**
     * @param  list<string>  $slots
     * @param  list<array{name: string, amount: string}>|null  $ingredients
     * @param  list<string>|null  $steps
     * @return array<string, mixed>
     */
    private function dish(
        string $name,
        string $slug,
        string $emoji,
        string $summary,
        array $slots,
        bool $light,
        bool $main,
        bool $dineOut,
        bool $cookHome,
        FiveElement $element,
        int $kcal,
        int $grams,
        ?int $cookMinutes,
        ?array $ingredients,
        ?array $steps,
        string $benefits,
        string $harms,
        string $advice,
        string $keywords,
    ): array {
        return [
            'name' => $name,
            'slug' => $slug,
            'emoji' => $emoji,
            'summary' => $summary,
            'meal_slots' => $slots,
            'supports_light' => $light,
            'supports_main' => $main,
            'supports_dine_out' => $dineOut,
            'supports_cook_home' => $cookHome,
            'five_element' => $element,
            'calories_kcal' => $kcal,
            'serving_grams' => $grams,
            'cook_minutes' => $cookMinutes,
            'ingredients' => $ingredients,
            'steps' => $steps,
            'benefits' => $benefits,
            'harms' => $harms,
            'advice' => $advice,
            'notes' => null,
            'search_keywords' => $keywords,
        ];
    }
}
